version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    nodejs: "16"
  jobs:
    post_install:
      - npm install -g @mermaid-js/mermaid-cli
sphinx:
  configuration: conf.py
python:
   install:
     - requirements: requirements.txt
