packet-beta
    title Level 0
        0-7: "HDF5 File Signature"
        8: "Version # of Super Block"
        9: "Version # of Global Free-space Storage"
        10: "Version # of Group"
        11: "Reserved"
        12: "Version # of Shared Header Message Format"
        13: "Size of Offsets"
        14: "Size of Lengths"
        15: "Reserved (zero)"
        
        
